### ISSUE TITLE
Add c2hs as dependency

### ISSUE THREAD

**Issue by wyager** [adamwalker/hrtlsdr#1]
I think my build failed because I didn't have `c2hs` installed, but it's not listed as a dependency. You probably installed it at some other time, and it was in your PATH even if you tested using a fresh sandbox.

**Comment by adamwalker** [comment]
It is listed as a dependency in the build-tools field of the cabal file.

Unfortunately, I believe Cabal doesnt automatically install build-tools dependencies so you have to do it manually, see:

https://github.com/haskell/cabal/issues/220

**Comment by wyager** [comment]
Oh well. Thanks#
